### ISSUE TITLE
Minecraft keeps sending me to the title screen every 10-30 min or so

### ISSUE THREAD

**Issue by CrossThyBread** [Patrigan/FactionCraft#36] opened 2023-04-09 20:48 UTC
---- Minecraft Crash Report ----
// My bad.

Time: 4/9/23, 11:07 PM
Description: Exception ticking world

java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:153) ~[?:?] {re:mixin}
	at java.util.AbstractList.add(AbstractList.java:111) ~[?:?] {re:mixin}
	at com.patrigan.faction_craft.faction.EntityWeightMapProperties.addAllowedRank(EntityWeightMapProperties.java:41) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at com.patrigan.faction_craft.world.spawner.PatrolSpawner.spawnPatrolMember(PatrolSpawner.java:116) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at com.patrigan.faction_craft.world.spawner.PatrolSpawner.spawnPatrol(PatrolSpawner.java:98) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at com.patrigan.faction_craft.world.spawner.PatrolSpawner.m_7995_(PatrolSpawner.java:76) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8799_(ServerLevel.java:357) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:faction_craft.mixins.json:ServerLevelAccessor,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:366) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:309) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:faction_craft.mixins.json:ServerLevelAccessor,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.AbstractList.add(AbstractList.java:153) ~[?:?] {re:mixin}
	at java.util.AbstractList.add(AbstractList.java:111) ~[?:?] {re:mixin}
	at com.patrigan.faction_craft.faction.EntityWeightMapProperties.addAllowedRank(EntityWeightMapProperties.java:41) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at com.patrigan.faction_craft.world.spawner.PatrolSpawner.spawnPatrolMember(PatrolSpawner.java:116) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at com.patrigan.faction_craft.world.spawner.PatrolSpawner.spawnPatrol(PatrolSpawner.java:98) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at com.patrigan.faction_craft.world.spawner.PatrolSpawner.m_7995_(PatrolSpawner.java:76) ~[faction_craft-1.18.2-1.1.8.jar%2386!/:1.18.2-1.1.8] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8799_(ServerLevel.java:357) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:faction_craft.mixins.json:ServerLevelAccessor,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:366) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:309) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:281) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:faction_craft.mixins.json:ServerLevelAccessor,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['MeetTheEnginner_'/58, l='ServerLevel[New World]', x=398.31, y=69.00, z=656.48]]
	Chunk stats: 4490
	Level dimension: minecraft:overworld
	Level spawn location: World: (336,64,32), Section: (at 0,0,0 in 21,4,2; chunk contains blocks 336,-64,32 to 351,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 224344 game time, 347018 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 32864 (now: false), thunder time: 38256 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
	Player Count: 1 / 8; [ServerPlayer['MeetTheEnginner_'/58, l='ServerLevel[New World]', x=398.31, y=69.00, z=656.48]]
	Data Packs: vanilla, mod:betterdungeons, mod:notenoughcrashes (incompatible), mod:fallingthrough (incompatible), mod:connectiblechains, mod:villagerdrops (incompatible), mod:areas, mod:jei (incompatible), mod:siegemachines, mod:dungeons_mobs (incompatible), mod:kingvillager, mod:rubidium (incompatible), mod:immersive_weathering (incompatible), mod:forgeendertech, mod:aileron (incompatible), mod:harderbranchmining (incompatible), mod:ctm (incompatible), mod:prism (incompatible), mod:placebo (incompatible), mod:integrated_api, mod:comforts (incompatible), mod:timber_frames, mod:yungsapi, mod:gateways (incompatible), mod:feature_nbt_deadlock_be_gone (incompatible), mod:create_confectionery, mod:guardvillagers (incompatible), mod:blueprint (incompatible), mod:savage_and_ravage (incompatible), mod:rubidium_extras (incompatible), mod:knight_quest, mod:cloth_config (incompatible), mod:sound_physics_remastered (incompatible), mod:villagercomfort, mod:travelerstitles, mod:despawningeggshatch, mod:chalk (incompatible), mod:createcafe (incompatible), mod:idas, mod:selene (incompatible), mod:supplementaries (incompatible), mod:zillagersweararmor (incompatible), mod:undead_expansion, mod:taxov, mod:amplifiednether, mod:morevillagers, mod:terrablender (incompatible), mod:weaponmaster, mod:domum_ornamentum (incompatible), mod:hostilevillages (incompatible), mod:rottencreatures (incompatible), mod:iceberg (incompatible), mod:flywheel (incompatible), mod:alloyed (incompatible), mod:create, mod:createdeco (incompatible), mod:curios (incompatible), mod:legendarytooltips (incompatible), mod:blockui (incompatible), mod:collective (incompatible), mod:workers (incompatible), mod:autoreglib (incompatible), mod:sit (incompatible), mod:randomvillagenames, mod:villagersellanimals, mod:spells_and_shields, mod:betterstrongholds, mod:eatinganimation, mod:forge, mod:quark (incompatible), mod:architectury (incompatible), mod:antiqueatlas (incompatible), mod:alexsdelight, mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:farmersdelight (incompatible), mod:nethersdelight (incompatible), mod:farmersrespite (incompatible), mod:create_crystal_clear, mod:chimes (incompatible), mod:adchimneys, mod:bettergolem, mod:smallships (incompatible), mod:villagesecurity, mod:t_and_t, mod:geckolib3 (incompatible), mod:nebs (incompatible), mod:dungeons_libraries (incompatible), mod:recruits (incompatible), mod:wwoo_forge (incompatible), Immersive Weathering Generated Pack, Supplementaries Generated Pack, config_pack, file/Villager_King_the_Peacekeeper.zip (incompatible), file/nogear4u.zip (incompatible), mod:snowrealmagic, mod:kiwi, mod:faction_craft (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		Kiwi-1.18.2-forge-6.1.3.jar                       |Kiwi                          |kiwi                          |6.1.3               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.2.0+1.18.2-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.2.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		fallingthrough-1.18.2-2.4.jar                     |Fallingthrough mod            |fallingthrough                |1.18.2-2.4          |DONE      |Manifest: NOSIGNATURE
		Connectible Chains-forge-1.18.2-2.1.1.jar         |Connectible Chains            |connectiblechains             |2.1.1               |DONE      |Manifest: NOSIGNATURE
		villagerdrops-forge-1.18.2-v1.0.1.jar             |Villagers Drop Emeralds on Dea|villagerdrops                 |1.18.2              |DONE      |Manifest: NOSIGNATURE
		areas-1.18.2-4.3.jar                              |Areas                         |areas                         |4.3                 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |DONE      |Manifest: NOSIGNATURE
		[1.18.2]-Medieval-Siege-Machines-v1.14.jar        |Medieval Siege Machines       |siegemachines                 |0.0.1-1.18.2        |DONE      |Manifest: NOSIGNATURE
		dungeons_mobs-1.18.2-3.0.2-beta.jar               |Dungeons Mobs                 |dungeons_mobs                 |1.18.2-3.0.2-beta   |DONE      |Manifest: NOSIGNATURE
		kingvillager-1.10.jar                             |The King of the Village       |kingvillager                  |1.10                |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.5.jar                                |Rubidium                      |rubidium                      |0.5.5               |DONE      |Manifest: NOSIGNATURE
		immersive_weathering-1.18.2-3.0.3-forge.jar       |Immersive Weathering          |immersive_weathering          |1.18.2-1.18.2-3.0.3 |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.18.2-9.0.6.0-build.1400.jar      |ForgeEndertech                |forgeendertech                |9.0.6.0             |DONE      |Manifest: NOSIGNATURE
		aileron-1.18.2-forge-1.0.2.jar                    |Aileron                       |aileron                       |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		HarderBranchMining-1.18.2-1.40.0.14.jar           |Harder Branch Mining Mod      |harderbranchmining            |1.18.2-1.40.0.14    |DONE      |Manifest: NOSIGNATURE
		CTM-1.18.2-1.1.5+5.jar                            |ConnectedTexturesMod          |ctm                           |1.18.2-1.1.5+5      |DONE      |Manifest: NOSIGNATURE
		Prism-1.18.2-1.0.1.jar                            |Prism                         |prism                         |1.0.1               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.6.6.jar                          |Placebo                       |placebo                       |6.6.6               |DONE      |Manifest: NOSIGNATURE
		integrated_api_forge-1.2.7+1.18.2.jar             |Integrated API                |integrated_api                |1.2.7+1.18.2        |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.6.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.6      |DONE      |Manifest: NOSIGNATURE
		Timber_Frames_1.18.2_1.5_CTM.jar                  |Timber Frames                 |timber_frames                 |1.4.1               |DONE      |Manifest: NOSIGNATURE
		faction_craft-1.18.2-1.1.8.jar                    |Faction Craft                 |faction_craft                 |1.18.2-1.1.8        |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.9.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.9  |DONE      |Manifest: NOSIGNATURE
		GatewaysToEternity-1.18.2-2.2.1.jar               |Gateways To Eternity          |gateways                      |2.2.1               |DONE      |Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		create-confectionery1.18.2_v1.0.8.jar             |Create Confectionery          |create_confectionery          |1.0.8               |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		SnowRealMagic-1.18.2-forge-4.2.4.jar              |Snow! Real Magic!             |snowrealmagic                 |4.2.4               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.1.jar                |Savage & Ravage               |savage_and_ravage             |4.0.1               |DONE      |Manifest: NOSIGNATURE
		rubidium_extras-1.18.2_v1.3.2.jar                 |Rubidium Extras               |rubidium_extras               |1.18.2_v1.3.2       |DONE      |Manifest: NOSIGNATURE
		KnightQuest1.1.7.Patch.jar                        |Knight Quest                  |knight_quest                  |1.1.6               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		Villager Comfort-1.18.2-1.0.1.jar                 |Villager Comfort              |villagercomfort               |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		TravelersTitles-1.18.2-Forge-2.1.1.jar            |Traveler's Titles             |travelerstitles               |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		despawningeggshatch-1.18.2-4.1.jar                |Despawning Eggs Hatch         |despawningeggshatch           |4.1                 |DONE      |Manifest: NOSIGNATURE
		chalk-1.18.2-1.4.0.jar                            |Chalk                         |chalk                         |1.4.0               |DONE      |Manifest: NOSIGNATURE
		createcafe-1.9.6-1.18.2.jar                       |Create Cafe                   |createcafe                    |1.9.6-1.18.2        |DONE      |Manifest: NOSIGNATURE
		idas_forge-1.6.3+1.18.2.jar                       |Integrated Dungeons and Struct|idas                          |1.6.3+1.18.2        |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.16.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.16       |DONE      |Manifest: NOSIGNATURE
		illagersweararmor-1.1.5.jar                       |Illagers Wear Armor           |zillagersweararmor            |1.1.5               |DONE      |Manifest: NOSIGNATURE
		UndeadExpansion_2.0.4_1.18.2_b.jar                |Undead Expansion              |undead_expansion              |2.0.4               |DONE      |Manifest: NOSIGNATURE
		TaxOceanVillager+M.1.18+ForM-1.1.2.jar            |Tax' Ocean Villager           |taxov                         |1.1.2               |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_v1.1.1.jar                       |Amplified Nether              |amplifiednether               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.18.2-3.3.2.jar              |More Villagers                |morevillagers                 |3.3.2               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |DONE      |Manifest: NOSIGNATURE
		weaponmaster-multi-forge-1.18.1-3.0.3.jar         |YDM's Weapon Master           |weaponmaster                  |3.0.3               |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA |DONE      |Manifest: NOSIGNATURE
		hostilevillages-1.18.2-4.1.jar                    |Example Mod                   |hostilevillages               |1.18.2-4.1          |DONE      |Manifest: NOSIGNATURE
		rottencreatures-forge-1.18.2-1.0.0.jar            |Rotten Creatures              |rottencreatures               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.2-forge-1.0.49.jar                   |Iceberg                       |iceberg                       |1.0.49              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |DONE      |Manifest: NOSIGNATURE
		alloyed-1.18.2-v1.4e.jar                          |Create: Alloyed               |alloyed                       |1.18.2              |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		createdeco-1.3.0-1.18.2.jar                       |Create Deco                   |createdeco                    |1.3.0-1.18.2        |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.0      |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.18.2-1.3.1.jar                |Legendary Tooltips            |legendarytooltips             |1.3.1               |DONE      |Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.47-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.47-ALPHA |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-6.53.jar                        |Collective                    |collective                    |6.53                |DONE      |Manifest: NOSIGNATURE
		workers-1.18.2-1.5.2.jar                          |Workers Mod                   |workers                       |1.5.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		sit-1.18.2-1.3.3.jar                              |Sit                           |sit                           |1.3.3               |DONE      |Manifest: NOSIGNATURE
		randomvillagenames-1.18.2-3.2.jar                 |Random Village Names          |randomvillagenames            |3.2                 |DONE      |Manifest: NOSIGNATURE
		nocube's_villagers_sell_animals_1.2.0_forge_1.18.2|Villagers Sell Animals (by NoC|villagersellanimals           |1.2.0               |DONE      |Manifest: NOSIGNATURE
		spells_and_shields-1.18.2-1.10.2-LEGACY.jar       |Spells & Shields              |spells_and_shields            |1.18.2-1.10.2-LEGACY|DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		eatinganimation-1.18.2-2.2.0.jar                  |Eating Animation              |eatinganimation               |2.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.1-universal.jar                 |Forge                         |forge                         |40.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.90-forge.jar                    |Architectury                  |architectury                  |4.11.90             |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-7.1.1-forge-mc1.18.2.jar             |Antique Atlas                 |antiqueatlas                  |7.1.1-forge-mc1.18.2|DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.18.2-1.3.3.jar                     |Alex's Delight                |alexsdelight                  |1.3.3               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		create_crystal_clear-0.1.3e-1.18.2.jar            |Create: Crystal Clear         |create_crystal_clear          |1.18.2-0.1.3e       |DONE      |Manifest: NOSIGNATURE
		Chimes-1.1.2-1.18.2.jar                           |Chimes                        |chimes                        |1.1.2               |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.18.2-8.3.5.0-build.1400.jar          |Advanced Chimneys             |adchimneys                    |8.3.5.0             |DONE      |Manifest: NOSIGNATURE
		bettergolem-1.18.2-1.1.0.jar                      |Better Golem                  |bettergolem                   |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		smallships-1.18.2-2.0.0-Alpha-0.4.jar             |Small Ships Mod               |smallships                    |2.0.0-a0.4          |DONE      |Manifest: NOSIGNATURE
		villagesecurity-1.18.2-1.2.jar                    |Tightened Village Security    |villagesecurity               |1.2                 |DONE      |Manifest: NOSIGNATURE
		towns_and_towers_forge-1.10.0.1+1.18.2.jar        |Towns and Towers              |t_and_t                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		NekosEnchantedBooks-1.18.2-1.8.0.jar              |Neko's Enchanted Books        |nebs                          |1.8.0               |DONE      |Manifest: NOSIGNATURE
		dungeons_libraries-1.18.2-2.0.5-beta.jar          |Dungeons Libraries            |dungeons_libraries            |1.18.2-2.0.5-beta   |DONE      |Manifest: NOSIGNATURE
		recruits-1.18.2-1.9.3.8.jar                       |Recruits Mod                  |recruits                      |1.9.3.8             |DONE      |Manifest: NOSIGNATURE
		wwoo-2.6.3-FORGE-1.18.2.jar                       |William Wythers Overhauled Ove|wwoo_forge                    |2.6.3               |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 60e6cca5-48d6-4469-86c6-5fdd9f2f151a
	FML: 40.2
	Forge: net.minecraftforge:40.2.1
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
	Suspected Mods: None

The last crash report , i think is a problem with the factioncraft mod , at  first in another crash report it said it was a prob with the dungeon mods(dungeon gear and mobs) but now is only a problem with factioncraft (i think) and it keeps sending me to the title screen and saying ''server closed'' in the multiplayer menu

**Comment by Patrigan** [comment] 2023-06-02 08:27
Duplicate of #39 Please follow that one for tracking of bugfix.

**Closed as completed by Patrigan** 2023-06-02 08:27 UTC
